FROM node:20-slim

# تثبيت الاعتماديات داخل حاوية node-slim
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY *.js ./

CMD ["node", "index.js"]
